=== joy-y-cheng/medleys-website/schemas/service-info-list.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "title": "Service Info",
    "type": "array",
    "description": "Information about organization Medleys works with",
    "items": {
        "type": "object",
        "properties": {
            "organization": {
                "type": "string",
                "description": "The name of the organization"
            },
            "slug": {
                "type": "string",
                "description": "Slugified name, e.g., lowercased and delimited with hyphens, used to identify the picture(s)"
            },
            "description": {
                "type": "string",
                "description": "Description of how Medleys works with the organization"
            },
            "images": {
                "type": "integer",
                "description": "The number of images to use for the carousel",
                "minimum": 0
            },
            "links": {
                "type": "array",
                "description": "The list of links associated with the organization and Medleys' involvement",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {
                            "type": "string",
                            "description": "The text to display"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri",
                            "description": "The link associated with the text"
                        }
                    },
                    "required": [
                        "text",
                        "url"
                    ],
                    "additionalProperties": false
                }
            }
        },
        "required": [
            "organization",
            "slug",
            "description",
            "images",
            "links"
        ],
        "additionalProperties": false
    }
}

=== joy-y-cheng/medleys-website/src/_data/service-info-list.json
[
    {
        "organization": "Love Notes",
        "slug": "love-notes",
        "description": "Every year during the week of Valentine's Day, we raise money for the Downtown Women's Center through our Love Notes fundraiser during which we offer live and virtual serenades. In 2026, we delivered over 100 Love Notes and raised almost $2,000! You can support our cause by ordering a Love Note for a loved one in February.",
        "images": 4,
        "links":
        [
            {
                "text": "Learn more about Love Notes",
                "url": "https://medleysacappella.org/love-notes"
            },
            {
                "text": "Learn more about the Downtown Women's Center",
                "url": "https://downtownwomenscenter.org/"
            }
        ]
    },
    {
        "organization": "UCLA Health × UCLA People-Animal Connection",
        "slug": "people-animal-connection",
        "description": "We have the honor of caroling for the amazing patients and dedicated staff at Ronald Reagan UCLA Medical Center and UCLA Santa Monica Medical Center alongside UCLA People-Animal Connection's talented dogs and wonderful team. We sing classic Christmas and Hanukkah carols for the December holidays and some of our Love Notes songs for Valentine's Day.",
        "images": 6,
        "links":
        [
            {
                "text": "Learn more about UCLA People-Animal Connection",
                "url": "https://www.uclahealth.org/programs/pac"
            },
            {
                "text": "Read about us on KNX News",
                "url": "https://www.audacy.com/knxnews/news/local/dogs-visit-kids-at-ucla-medical-center-for-valentines-day"
            }
        ]
    },
    {
        "organization": "Reading to Kids",
        "slug": "reading-to-kids",
        "description": "We enjoy reading to students with the volunteers at Reading to Kids at various elementary schools in Los Angeles, including MacArthur Park Elementary School and Magnolia Avenue Elementary School. Every year since 2024, we have performed our setlist at Reading to Kids' March \"Music and Entertainment\"-themed reading club.",
        "images": 2,
        "links":
        [
            {
                "text": "Learn more about Reading to Kids",
                "url": "https://readingtokids.org/main/main.php"
            }
        ]
    },
    {
        "organization": "Downtown Women's Center",
        "slug": "dwc",
        "description": "We love singing for the incredible women at the Downtown Women's Center. Every year starting in 2024, we have celebrated the success of our annual Love Notes fundraiser by showcasing some of our love songs. We also have the privilege of caroling at the Downtown Women's Center during the holiday season and performing for Mother's Day.",
        "images": 4,
        "links":
        [
            {
                "text": "Learn more about the Downtown Women's Center",
                "url": "https://downtownwomenscenter.org/"
            }
        ]
    },
    {
        "organization": "Assistance League of Los Angeles Preschool Learning Center",
        "slug": "alla-preschool",
        "description": "Ever since 2024, we have had the joy of singing for and with the children at Assistance League of Los Angeles's Preschool Learning Center! In the winter, we sing carols, and in the spring, we share some fun songs from our setlist. We also enjoy teaching the children some of our favorite musical rounds.",
        "images": 3,
        "links":
        [
            {
                "text": "Learn more about the Preschool Learning Center",
                "url": "https://assistanceleaguela.org/preschool-learning-center/"
            }
        ]
    },
    {
        "organization": "Wise & Healthy Aging",
        "slug": "waha",
        "description": "Every winter, we visit the Senior and Adult Day Center at Wise & Healthy Aging in December and sing carols to spread holiday cheer! Every spring, we share some songs from our Love Notes setlist to celebrate Valentine's Day with the individuals there.",
        "images": 2,
        "links":
        [
            {
                "text": "Learn more about Wise & Healthy Aging",
                "url": "https://www.wiseandhealthyaging.org/"
            }
        ]
    },
    {
        "organization": "UCLA Health × Chase Child Life Program",
        "slug": "chase-child-life",
        "description": "Several times a year, we visit the pediatric unit at the UCLA Santa Monica Medical Center and have the honor of singing for the patients as part of the Chase Child Life Program. We sing a mix of uplifting songs as well as carols during the holiday season to help ease the stress of a hospital stay.",
        "images": 1,
        "links":
        [
            {
                "text": "Learn more about the Chase Child Life Program",
                "url": "https://www.chasefoundation.org/chase_child_life_program"
            }
        ]
    },
    {
        "organization": "Los Angeles Mission",
        "slug": "la-mission",
        "description": "Every winter, we host a clothing drive during our holiday concert and collect clothing donations for Los Angeles Mission.",
        "images": 4,
        "links":
        [
            {
                "text": "Learn more about Los Angeles Mission",
                "url": "https://losangelesmission.org/"
            }
        ]
    },
    {
        "organization": "Los Angeles Unified School District",
        "slug": "lausd",
        "description": "Every spring, we organize a school supplies drive during our final concert and donate school supplies to the Los Angeles Unified School District's Homeless Education Office.",
        "images": 3,
        "links":
        [
            {
                "text": "Learn more about the Homeless Education Office",
                "url": "https://www.lausd.org/heo"
            }
        ]
    },
    {
        "organization": "Habitat for Humanity × UCLA Bruin Belles Service Association",
        "slug": "habitat-for-humanity",
        "description": "We competed in UCLA Bruin Belles Service Association's first-ever charity dodgeball tournament—the 2024 BelleBall Tournament—and won! As the winners, we had the opportunity to donate $1,000 to a charity of our choice. We chose Habitat for Humanity as the charity to receive the donation.",
        "images": 3,
        "links":
        [
            {
                "text": "Learn more about Habitat for Humanity",
                "url": "https://www.habitat.org/"
            },
            {
                "text": "Learn more about UCLA Bruin Belles Service Association",
                "url": "https://www.bruinbelles.com/"
            }
        ]
    },
    {
        "organization": "Assistance League of Los Angeles Family Day of Service",
        "slug": "alla",
        "description": "We joined Assistance League of Los Angeles in November 2024 for their Family Day of Service: \"Sweet Dreams and Cozy Nights\"! We made no-sew blankets for unhoused and foster youth in Los Angeles.",
        "images": 3,
        "links":
        [
            {
                "text": "Learn more about Assistance League of Los Angeles",
                "url": "https://assistanceleaguela.org/"
            }
        ]
    },
    {
        "organization": "L.A. Cancer Challenge",
        "slug": "lacc",
        "description": "In October 2024, we helped set up for the 27th Annual 5K Walk/Run which supports the Hirshberg Foundation for Pancreatic Cancer Research.",
        "images": 2,
        "links":
        [
            {
                "text": "Learn more about the L.A. Cancer Challenge",
                "url": "http://lacancerchallenge.com/"
            },
            {
                "text": "Learn more about the Hirshberg Foundation for Pancreatic Cancer Research",
                "url": "https://pancreatic.org/"
            }
        ]
    },
    {
        "organization": "Children's Hunger Fund",
        "slug": "hunger-fund",
        "description": "We volunteered at the Children's Hunger Fund for UCLA Volunteer Day in October 2024!",
        "images": 2,
        "links":
        [
            {
                "text": "Learn more about the Children's Hunger Fund",
                "url": "https://childrenshungerfund.org/"
            }
        ]
    },
    {
        "organization": "Pediatric AIDS Coalition",
        "slug": "pediatric-aids-coalition",
        "description": "We performed virtually for Dance Marathon at UCLA in 2020 to support the Pediatric AIDS Coalition's mission to fundraise for and raise awareness about the fight against AIDS in children.",
        "images": 2,
        "links":
        [
            {
                "text": "Learn more about the Pediatric AIDS Coalition",
                "url": "https://pediatricaidscoalition.org/"
            },
            {
                "text": "Watch Dance Marathon 2020",
                "url": "https://www.youtube.com/watch?v=6nSl4-zXSRo"
            }
        ]
    },
    {
        "organization": "Providence Saint John's Health Center",
        "slug": "saint-johns",
        "description": "In 2019, we were honored to sing for the patients and hardworking staff at Providence Saint John's Health Center in Santa Monica.",
        "images": 3,
        "links":
        [
            {
                "text": "Learn more about Saint John's Health Center Foundation",
                "url": "https://saintjohnsfoundation.org/"
            }
        ]
    }
]
